CONFIG_GPIO=y
CONFIG_BOOTLOADER_STMBOOT=y
CONFIG_FLASH=y
CONFIG_BOOTLOADER_MCUBOOT=n

CONFIG_FLASH_STM32_WRITE_PROTECT=n
CONFIG_FLASH_STM32_READOUT_PROTECTION=n
CONFIG_REBOOT=y
# slot a
CONFIG_FLASH_LOAD_OFFSET=0x6000
# slot b
# CONFIG_FLASH_LOAD_OFFSET=0x12000 